output_dir: ./exp0_20__/rgb_3d_hmdb
encryption_key: nvidia_tlt
gpu_ids: [0, 1, 2, 3, 4, 5, 6, 7]
model_config:
  model_type: rgb
  input_type: "3d"
  backbone: i3d
  rgb_seq_length: 64
  rgb_pretrained_model_path: /workspace/action_recognition/i3d_pretrained/rgb_imagenet_kinetics.pt
  rgb_pretrained_num_classes: 400
  sample_strategy: consecutive
  sample_rate: 1
train_config:
  optim:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0000001
    lr_steps: [12, 25]
    lr_decay: 0.1
  epochs: 35
dataset_config:
  train_dataset_dir: /raid/HMDB51_splitted_org/train
  val_dataset_dir: /raid/HMDB51_splitted_org/test
  label_map:
    throw: 0
    push: 1
    dribble: 2
    shoot_gun: 3
    hug: 4
    smile: 5
    fall_floor: 6
    chew: 7
    turn: 8
    cartwheel: 9
    stand: 10
    draw_sword: 11
    drink: 12
    eat: 13
    talk: 14
    climb: 15
    smoke: 16
    pick: 17
    shake_hands: 18
    pushup: 19
    swing_baseball: 20
    somersault: 21
    walk: 22
    flic_flac: 23
    run: 24
    ride_horse: 25
    sit: 26
    kiss: 27
    situp: 28
    hit: 29
    handstand: 30
    climb_stairs: 31
    pour: 32
    shoot_bow: 33
    kick_ball: 34
    brush_hair: 35
    sword_exercise: 36
    dive: 37
    fencing: 38
    golf: 39
    sword: 40
    shoot_ball: 41
    clap: 42
    punch: 43
    catch: 44
    jump: 45
    kick: 46
    ride_bike: 47
    wave: 48
    laugh: 49
    pullup: 50
  output_shape:
  - 224
  - 224
  batch_size: 8
  workers: 8
  augmentation_config:
    train_crop_type: random_crop
    horizontal_flip_prob: 0.5
    rgb_input_mean: [0.485, 0.456, 0.406]
    rgb_input_std: [0.229, 0.224, 0.225]
    val_center_crop: True
